#!/bin/bash

# requires UPNP_SERVICE, UPNP_PORT_EXT, UPNP_PORT_INT, UPNP_PROTOCOL

ADDRESS=`ip address | grep 192 | awk '{ print $2; }'`
CHECK=`/usr/bin/upnpc -L | grep $UPNP_SERVICE`
if [ -z "$CHECK" ]; then
        /usr/bin/upnpc -e $UPNP_SERVICE -r $UPNP_PORT_INT $UPNP_PORT_EXT $UPNP_PROTOCOL > /dev/null
elif [[ "$CHECK" != *"$ADDRESS"* ]] || [[ "$CHECK" != *"$UPNP_PORT_EXT"* ]] || [[ "$CHECK" != *"$UPNP_PORT_INT"* ]]; then
        /usr/bin/upnpc -d $UPNP_PORT_EXT $UPNP_PROTOCOL > /dev/null > /dev/null
        /usr/bin/upnpc -e $UPNP_SERVICE -r $UPNP_PORT_INT $UPNP_PORT_EXT $UPNP_PROTOCOL > /dev/null
fi
